version: '2'
services:
  task_db:
    image: postgres
  task:
    build: .
    command: bash -c "sleep 5 && python manage.py migrate -v3 --no-input && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - task_db
