version: '2'
services:
  task_db:
    image: postgres
  task:
    build: .
    entrypoint: ./scripts/run_dev.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - task_db
