# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 20:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, null=True)),
                ('lock_id', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending_queue', 'Pending Queue'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('in_progress', 'In Progress'), ('failed_retrying', 'Failed - Retrying'), ('dequeued', 'Dequeued'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=17)),
                ('received_at', models.DateTimeField(null=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=8)),
                ('unique', models.CharField(max_length=255, null=True)),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run_every', models.CharField(max_length=255, null=True)),
                ('recurring_run_enabled', models.NullBooleanField()),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskDef',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Task definition name can only contain lowercase alphanumeric charaters, dashes, and underscores.', regex='^[a-z0-9\\-_]+$')])),
                ('priority_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], max_length=8), size=None)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=2048, null=True)),
                ('default_timeout', models.IntegerField(default=600)),
                ('max_attempts', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_defs',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_def',
            field=models.ForeignKey(db_column='task_def_name', on_delete=django.db.models.deletion.CASCADE, to='api.TaskDef'),
        ),
        # add conditionally unique constraint on tasks.unique - not currently available within django framework
        migrations.RunSQL("CREATE UNIQUE INDEX \"unique_task\" ON \"tasks\" (\"task_def_name\", \"unique\") WHERE (\"status\" NOT IN ('dequeued','failed','completed'));")
    ]
