# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='lock_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurring_run_enabled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='run_every',
        ),
        migrations.AddField(
            model_name='task',
            name='worker_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
