# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 01:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_worker_id_drop_some_task_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='received_at',
            new_name='locked_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('failed_retrying', 'Failed - Retrying'), ('dequeued', 'Dequeued'), ('failed', 'Failed'), ('completed', 'Completed')], default='queued', max_length=17),
        ),
        migrations.AlterField(
            model_name='taskdef',
            name='priority_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], max_length=8), default=['normal'], size=None),
        ),
    ]
